module.exports = {
    devServer:{
        open:true,
        port:3000,
        overlay:false,
        proxy:{
            '/api':{
                target:'https://api.iynn.cn/film/api/v1',
                changeOrigin:true,
                pathRewrite:{
                    '^/api':''
                }
            },
            '/v1':{
                target:'http://127.0.0.1:8080',
                changeOrigin:true,
                pathRewrite:{
                    '^/v1':''
                }
            }
        }
    }
}